### ISSUE TITLE
Remove deployment bucket

### ISSUE THREAD

**Issue by estahn** [coyoteecd/serverless-s3-cleaner#1]
How do you reference the deployment bucket to be removed?

**Comment by coyoteecd** [comment]
@estahn I do not use the plugin for deployment buckets; I use it for cleaning up other S3 buckets that are part of a stack (e.g. buckets where we copy web app files). "Referencing" is by name - since the plugin has to execute before the stack is removed, you cannot use !Ref or stack outputs to read it.

Instead, you do it the other way around: put the bucket name in a config key, and use that config key in both the plugin config, and also in the AWS::S3::Bucket resource that is defined under `resources`.

**Comment by coyoteecd** [comment]
Closing as answered

**Comment by SaraPrager** [comment]
@coyoteecd, how can I pass a config key? could you please provide an example?
I get a warning of:
```
Warning: Invalid configuration encountered
 at 'custom.serverless-s3-cleaner.buckets.0': must be string
```
for any case that is not a standard string.

**Comment by coyoteecd** [comment]
@SaraPrager could you post the configuration that gives you that warning? The plugin does expect the bucket to be a string (either the name of a bucket, or a `${self:custom.nameOfKey}` reference to another property.

**Comment by SaraPrager** [comment]
This worked for me:
`
serverless-s3-cleaner:
  buckets:
    - "${param:env-name}-reports-${opt:region}-${opt:stage}"
`

**Comment by mcopik** [comment]
I'm experiencing the same issue - in our stack, we have an S3 bucket whose part of the name is the Stack ID to ensure the global uniqueness of the bucket name across all deployments and accounts. Thus, we have to depend on referencing the name from the stack itself.

I tried the following options, with and without quotation marks. None of them appears to work.

```yaml
  serverless-s3-cleaner:
    buckets:
      - "${self:resources.Resources.dataBucket.Properties.BucketName}"
      - "${self:provider.environment.S3_DATA_BUCKET}"
```

**Comment by coyoteecd** [comment]
@mcopik 

Using `${self:provider.environment}` appears to work correctly (I am using Serverless Framework v3.30.1). Maybe you're using another variable in that environment? Keep in mind that self:provider.environment is for lambda variables, if you want to pass something at build time, try using params as explained in the serverless docs, or use e.g. `${env:S3_DATA_BUCKET}`

Furthermore, you cannot use parameters from the stack itself in the buckets array. The reason is that serverless evaluates variables before it attempts to execute the command (deploy/remove/s3remove etc). So if you try to do something like this:

```
serverless-s3-cleaner:
    buckets:
       - "${cf:${self:service}-${self:provider.stage}:ServerlessDeploymentBucketName}"
```

where `ServerlessDeploymentBucketName` can in fact be any stack output variable, the initial deployment will fail because variables get executed before the stack gets deployed. I am not aware of a way to control how the variables are resolved so that they are only resolved for certain commands (resolution happens outside the plugin). If you figure something out, I'm open to PRs.

**Comment by mcopik** [comment]
@coyoteecd Thank you for the detailed explanation! I was not aware of this limitation of the Serverless Framework. 

Unfortunately, we need to make bucket names unique since two users using the same stack name will cause a bucket name collision. We ended up using a Python script using `boto3` to manually clean the bucket before removal.
